//
//  MapInteractor.swift
//  WeatherMap
//
//  Created by Kamil Chmiel on 18.10.2018.
//  Copyright (c) 2018 kamilchmiel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MapBusinessLogic
{
  func fetchWeather(request: Map.FetchWeather.Request)
}

protocol MapDataStore
{
  //var name: String { get set }
}

class MapInteractor: MapBusinessLogic, MapDataStore
{
  var presenter: MapPresentationLogic?
  var worker: MapWorker?
  
  // MARK: Fetch weather
  
  func fetchWeather(request: Map.FetchWeather.Request)
  {
    worker = MapWorker()
    worker?.fetchWeatherData(lon: request.longitude, lat: request.latitude, save: request.save, completion: { (weatherData) in
        if let data = weatherData {
            let response = Map.FetchWeather.Response(weatherData: data)
            self.presenter?.presentFetchWeather(response: response)
        }
        else {
            self.presenter?.presentConnectionError()
        }
    })
  }
}
