//
//  MapModels.swift
//  WeatherMap
//
//  Created by Kamil Chmiel on 18.10.2018.
//  Copyright (c) 2018 kamilchmiel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Map
{
  // MARK: Use cases
  
  enum FetchWeather
  {
    struct Request
    {
        var latitude: Double
        var longitude: Double
        var save: Bool
    }
    struct Response
    {
        var weatherData: WeatherDataModel
    }
    struct ViewModel
    {
        var temperature: Int
        var city: String
        var desc: String
    }
  }
}
