//
//  MapPresenter.swift
//  WeatherMap
//
//  Created by Kamil Chmiel on 18.10.2018.
//  Copyright (c) 2018 kamilchmiel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MapPresentationLogic
{
    func presentFetchWeather(response: Map.FetchWeather.Response)
    func presentConnectionError()
}

class MapPresenter: MapPresentationLogic
{
    weak var viewController: MapDisplayLogic?
  
    // MARK: Do something
  
    func presentFetchWeather(response: Map.FetchWeather.Response)
    {
        let weatherData = response.weatherData
        let viewModel = Map.FetchWeather.ViewModel(temperature: weatherData.temperature, city: weatherData.city, desc: weatherData.desc)
        viewController?.displayWeather(viewModel: viewModel)
    }
    
    func presentConnectionError() {
        viewController?.displayConnectionError()
    }
}
