//
//  LocationsPresenter.swift
//  WeatherMap
//
//  Created by Kamil Chmiel on 18.10.2018.
//  Copyright (c) 2018 kamilchmiel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LocationsPresentationLogic
{
  func presentFetchLocations(response: Locations.FetchLocations.Response)
}

class LocationsPresenter: LocationsPresentationLogic
{
  weak var viewController: LocationsDisplayLogic?
  
  // MARK: Do something
  
  func presentFetchLocations(response: Locations.FetchLocations.Response)
  {
    if let locations = response.locations {
        let displayedLocations = Array(locations).map { (location) -> Locations.FetchLocations.ViewModel.DisplayedLocation in
            return Locations.FetchLocations.ViewModel.DisplayedLocation(name: location.name, latitude: location.latitude, longitude: location.longitude)
        }
    let viewModel = Locations.FetchLocations.ViewModel(displayedLocations: displayedLocations)
    viewController?.displayFetchLocations(viewModel: viewModel)
    }
  }
}
