//
//  LocationsInteractor.swift
//  WeatherMap
//
//  Created by Kamil Chmiel on 18.10.2018.
//  Copyright (c) 2018 kamilchmiel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RealmSwift

protocol LocationsBusinessLogic
{
  func fetchLocations(request: Locations.FetchLocations.Request)
}

protocol LocationsDataStore
{
  //var name: String { get set }
}

class LocationsInteractor: LocationsBusinessLogic, LocationsDataStore
{
    var presenter: LocationsPresentationLogic?
    var worker: LocationsWorker?
    
    // MARK: Fetch locations
    
    var locations: Results<LocationModel>?
    
    func fetchLocations(request: Locations.FetchLocations.Request)
    {
        if locations?.realm == nil {
            let realm = try! Realm()
            locations = realm.objects(LocationModel.self)
        }
        let response = Locations.FetchLocations.Response(locations: locations)
        presenter?.presentFetchLocations(response: response)
    }
    
}
