//
//  LocationsModels.swift
//  WeatherMap
//
//  Created by Kamil Chmiel on 18.10.2018.
//  Copyright (c) 2018 kamilchmiel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RealmSwift

enum Locations
{
  // MARK: Use cases
  
  enum FetchLocations
  {
    struct Request
    {
    }
    struct Response
    {
        var locations: Results<LocationModel>?
    }
    struct ViewModel
    {
        struct DisplayedLocation
        {
            var name: String
            var latitude: Double
            var longitude: Double
        }
        var displayedLocations: [DisplayedLocation]
    }
  }
}
